### ISSUE TITLE
[bug] After update to latest cannot use auth

### ISSUE THREAD

**Issue by nvroot** [sourcebot-dev/sourcebot#265]
### Describe the bug

With Auth error:
```
[web] | [auth][error] JWTSessionError: Read more at [https://errors.authjs.dev#jwtsessionerror](https://errors.authjs.dev/#jwtsessionerror)
[web] | [auth][cause]: c: Invalid Compact JWE
[web] |     at eB (/app/packages/web/.next/server/chunks/8097.js:491:98380)
[web] |     at eW (/app/packages/web/.next/server/chunks/8097.js:491:100732)
[web] |     at Object.eJ [as decode] (/app/packages/web/.next/server/chunks/8097.js:491:101784)
[web] |     at r2 (/app/packages/web/.next/server/chunks/8097.js:491:45799)
[web] |     at r7 (/app/packages/web/.next/server/chunks/8097.js:491:52189)
[web] |     at async it (/app/packages/web/.next/server/chunks/8097.js:491:56772)
[web] |     at async X (/app/packages/web/.next/server/chunks/6657.js:1:23095)
[web] |     at async Q (/app/packages/web/.next/server/chunks/6657.js:1:22872)
[web] |     at async /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
[web] |     at async rE (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:8148)
[web] | [auth][details]: {}
```

### To reproduce

docker-compose:
```yaml
services:
  sourcebot:
    image: 'ghcr.io/sourcebot-dev/sourcebot:latest'
    container_name: sourcebot
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - './data:/data'
    environment:
      - CONFIG_PATH=/data/config.json
      - DATA_DIR=/data
      - SOURCEBOT_TELEMETRY_DISABLED=true # checked with and without
#      - ZOEKT_WEBSERVER_URL=https://source.site.com # checked with and without
      - AUTH_URL=https://source.site.com/api/auth/callback/github
      - SOURCEBOT_ENCRYPTION_KEY=hEcRW3atA22O6ecwgjjQtHxJ9HQ0V76        # openssl rand -base64 24
      - AUTH_SECRET=64x+5jyQMAHwKRFOQbdqfUANsSKNNSTebX5nai1M0xcO      # openssl rand -base64 33
      - SOURCEBOT_TENANCY_MODE=single
      - SOURCEBOT_AUTH_ENABLED=true
      - AUTH_CREDENTIALS_LOGIN_ENABLED=false
      - AUTH_GITHUB_CLIENT_ID=clientid
      - AUTH_GITHUB_CLIENT_SECRET=clientsecret
      - AUTH_TRUST_HOST=true   # checked with and without
    networks:
      - proxy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 60s
      timeout: 20s
      retries: 5
networks:
  proxy:
    external: true
```

### Sourcebot deployment information

Sourcebot version (e.g. v3.0.1):  3.0.2
