### ISSUE TITLE
Failed to clone repository

### ISSUE THREAD

**Issue by mstimvol** [sourcebot-dev/sourcebot#270]
When Sourcebot syncs my repositories (around 480), a few of them (8) are failing with the following error:

> [backend] | 2025-04-23T15:51:19.622Z error: [RepoManager] Failed to sync repository 447, attempt 2/3. Sleeping for 10s... Error: Error: Failed to clone repository

My conf looks like:

```
{
    "$schema": "https://raw.githubusercontent.com/sourcebot-dev/sourcebot/refs/heads/main/schemas/v3/index.json",
    "connections": {
        "some-connection1": {
            "type": "github",
            "repos": ["myorga/repo"],
            "revisions": {
                "branches": [
                    "main",
                    "stable_v1",
                    "stable_v2"
                ]
            }
        },
        "some-connection2": {
            "type": "github",
            "repos": ["Behat/Gherkin"]
        },
        "some-connection3": {
            "type": "gitlab",
            "token": {
                "env": "GITLAB_TOKEN"
            },
            "groups": [
                "plugins"
            ],
            "url": "https://my-self-hosted-instance.tld"
        }
    }
}
```

I first thought it's because of the API limit in Gitlab or because one or two projects are archived, but I figured out that it also fails to sync sometimes "some-connection1" and "some-connection2" and furthermore, the 8 repositories are always other repos - not the same. Any ideas why the indexing fails?

I'm using v3.0.4 of Sourcebot

**Comment by msukkari** [comment]
Hey Tim, sorry you're hitting this. Since the specific repos that are failing is changing I suspect this might be a networking issue when cloning the repos (I'm assuming the fail is happening during cloning not indexing from your error log). We've hit this before in certain environments where the networking is limited.

A workaround I would suggest you try is to drop the `maxRepoIndexingJobConcurrency` in the config: https://demo.sourcebot.dev/~/browse/github.com/sourcebot-dev/sourcebot@HEAD/-/blob/schemas/v3/index.json?highlightRange=46%3A1%2C50%3A19

Let me know if that helps!

**Comment by mstimvol** [comment]
Hi Michael, changing `maxRepoIndexingJobConcurrency` from 8 to 2 finally fixed the error. Thank you very much!

**Comment by securisec** [comment]
@msukkari having the same issue with gitea. Here is my quick test setup. The user `admin` has 4 repos in gitea. 

docker-compose.yml
```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: docker.gitea.com/gitea:1.23.7
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: no
    networks:
      - gitea
    volumes:
      - ./data:/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      # - "222:22"

  sourcebot:
    image: ghcr.io/sourcebot-dev/sourcebot:latest
    volumes: 
      - ./sb:/data
    networks:
      - gitea
    ports:
      - 3001:3000
    environment:
      - CONFIG_PATH=/data/config.json
      - GITEA_TOKEN=...

```

config.json
```json
{
  "$schema": "https://raw.githubusercontent.com/sourcebot-dev/sourcebot/refs/heads/main/schemas/v3/index.json",
  "settings": {
    "maxConnectionSyncJobConcurrency": 1,
    "maxRepoIndexingJobConcurrency": 2
  },
  "connections": {
    "connection-1": {
      "type": "gitea",
      "users": [
        "admin"
      ],
      "url": "http://gitea:3000",
      "token": {
        "env": "GITEA_TOKEN"
      }
    }
  }
}
```

The logs show
```
sourcebot-1  | [backend] | 2025-05-10T05:19:47.283Z error: [RepoManager] Failed to sync repository gitea:3000/admin/chepy (id: 2) after 3 attempts. Error: Error: Failed to clone repository
sourcebot-1  | [backend] | 2025-05-10T05:19:47.285Z error: [RepoManager] Failed to sync repository gitea:3000/admin/foo (id: 1) after 3 attempts. Error: Error: Failed to clone repository
```

In sourcebot, I do see that it touches the 4 repos (3 marked as private and all are failing). The repos are fine inside gitea itself. 

<img width="868" alt="Image" src="https://github.com/user-attachments/assets/df3e646b-4b00-459b-ab0d-af1ee52c2e52" />

To make sure it is not a network issue, I obtained a shell inside the sourcebot container, and can manually clone any of the repos via specifying the token as the password. 

Any suggestions would be great! Maybe a feature request, more verbose error messages would be wonderful.
